# this dockerfile is used for DEVELOPMENT ONLY
FROM golang:1.23.4-alpine3.19 AS builder

RUN apk --update add curl

RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
    sh -s -- -b $(go env GOPATH)/bin v1.55.2

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz && \
mv migrate /usr/local/bin/migrate

ENV GO111MODULE=on \
    GOOS=linux \
    CGO_ENABLED=0

EXPOSE 3001 3002
